### PR TITLE
Allow flags + Documentation

### PR DESCRIPTION
**Pull request by theovincent**
This PR is linked with this [issue](https://github.com/prewk/s3-cp-action/issues/1)

### CODE REVIEW

**Comment by prewk** [comment]
I'm sorry, I've had some very busy days, will get to this ASAP!

**Comment by theovincent** [comment]
@prewk Do you know when you will have time to look at the code? I don't want to press you, I understand that you have some other stuffs to do.

**Comment by prewk** [comment]
Yeah sorry again. Busy work, and toddler crazyness in the weekend/evening.

It looks really good, I'm just wondering - is it backwards compatible? Seems the env variables switched letter-case?

**Comment by theovincent** [comment]
No problem I understand fully! @prewk 

Concerning your comment, I changed my mind. I think it would be better to define the variables with *with* in stead of *env* like it is done by people from Google [here](https://github.com/google-github-actions/setup-gcloud) for example. Plus the fact that the changes I make for the file *action.yml* are telling to you to use *with* and not *env*. 

Then, I have to add *INPUT_* as a suffix of the environment variables in the file *entrypoint.sh* as the [documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith) says: 

> The variable is prefixed with INPUT_ and converted to upper case.

Otherwise, I can remove the changes that I have made on the file action.yml and put uppercases everywhere.

Tell me what you prefer? :)

**Comment by prewk** [comment]
Sure, the google way sounds fine. I guess I'll just have to bump it majorly (haven't looked into how GH action versioning works but a tag I guess.)

**Comment by theovincent** [comment]
Thank you for the answer @prewk.
You are right about the GitHub Action versioning. The [documentation](https://docs.github.com/en/actions/creating-actions/about-actions#using-release-management-for-actions) says so.

**Comment by theovincent** [comment]
@prewk I don't want to put pressure on you, I know that you have other things to do but I was wondering if you think you will have the time to merge this PR this week ? :)

**Comment by prewk** [comment]
Sorry about this.

I've merged and tagged `v2`, that should suffice, right?

**Comment by prewk** [comment]
(Thanks a lot for the contribution and patience!)

**Comment by theovincent** [comment]
No problem. Thank you and have a good day :)
I tried to use the action with the new tag and it [works perfectly](https://github.com/Deep-Learning-and-Aging/Website/runs/2882426025?check_suite_focus=true).

**Comment by prewk** [comment]
Good to hear!

**Pull request merged**
